export enum FileSystemStoreActionType {
  ADD_FOLDER = "ADD_FOLDER",
  ADD_FILE = "ADD_FILE",
  DELETE_NODE = "DELETE_NODE",
  RENAME_FILE = "RENAME_FILE",
  RENAME_FOLDER = "RENAME_FOLDER",
  TOGGLE_FOLDER_EXPANSION = "TOGGLE_FOLDER_EXPANSION",
}
